version: '3.9'

services:
  redis:
    image: redis
    restart: always
    container_name: 'redis'
    command: redis-server
    ports:
      - '6379:6379'
  web:
    build: .
    restart: always
    container_name: 'flaskapp'
    ports:
      - '5000:5000'
  celery:
    build: .
    container_name: 'celery'
    command: celery -A medicalapp.celery worker -B
    links:
      - redis
    depends_on:
      - web
      - redis